package com.chatapp.common.protocol;

/**
 * Enum định nghĩa các loại message trong giao thức
 * CẬP NHẬT: Thêm các type mới cho chức năng profile và friend
 */
public enum MessageType {
    // Authentication
    LOGIN_REQUEST,
    LOGIN_RESPONSE,
    REGISTER_REQUEST,
    REGISTER_RESPONSE,
    LOGOUT_REQUEST,
    LOGOUT_RESPONSE,
    FORGOT_PASSWORD_REQUEST,
    FORGOT_PASSWORD_RESPONSE,
    VERIFY_OTP_REQUEST,
    VERIFY_OTP_RESPONSE,
    RESEND_OTP_REQUEST,
    RESEND_OTP_RESPONSE,
    RESET_PASSWORD_REQUEST,      // THÊM
    RESET_PASSWORD_RESPONSE,

    // User Profile Management
    UPDATE_PROFILE_REQUEST,
    UPDATE_PROFILE_RESPONSE,
    CHANGE_PASSWORD_REQUEST,
    CHANGE_PASSWORD_RESPONSE,
    UPLOAD_AVATAR_REQUEST,
    UPLOAD_AVATAR_RESPONSE,
    GET_USER_INFO_REQUEST,
    GET_USER_INFO_RESPONSE,

    // Friend Management - CẬP NHẬT MỚI
    ADD_FRIEND_REQUEST,
    ADD_FRIEND_RESPONSE,
    ACCEPT_FRIEND_REQUEST,
    ACCEPT_FRIEND_RESPONSE,
    REJECT_FRIEND_REQUEST,
    REJECT_FRIEND_RESPONSE,
    UNFRIEND_REQUEST,
    UNFRIEND_RESPONSE,
    BLOCK_FRIEND_REQUEST,
    BLOCK_FRIEND_RESPONSE,
    GET_FRIENDS_REQUEST,
    GET_FRIENDS_RESPONSE,
    GET_PENDING_REQUESTS_REQUEST,
    GET_PENDING_REQUESTS_RESPONSE,
    SEARCH_USERS_REQUEST,
    SEARCH_USERS_RESPONSE,

    // Chat
    SEND_MESSAGE_REQUEST,
    SEND_MESSAGE_RESPONSE,
    RECEIVE_MESSAGE,
    GET_MESSAGES_REQUEST,
    GET_MESSAGES_RESPONSE,
    TYPING_INDICATOR,
    READ_RECEIPT,

    // File
    FILE_OFFER,
    FILE_ACCEPT,
    FILE_REJECT,
    FILE_INFO,

    // Call
    CALL_REQUEST,
    CALL_ACCEPT,
    CALL_REJECT,
    CALL_END,
    CALL_INFO,

    // Status
    STATUS_UPDATE,
    USER_ONLINE,
    USER_OFFLINE,

    RESPONSE,
    ERROR
}